# Generated by Django 6.0.7 on 2026-08-03 01:36

import accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('naran_kompletu', models.CharField(max_length=150, verbose_name='naran kompletu')),
                ('role', models.CharField(choices=[('ADMIN', 'Administradór'), ('PROFESSOR', 'Professór'), ('ESTUDANTE', 'Estudante')], default='PROFESSOR', max_length=20, verbose_name='role')),
                ('sexu', models.CharField(blank=True, choices=[('MANE', 'Mane'), ('FETO', 'Feto')], max_length=4, verbose_name='sexu')),
                ('kargu', models.CharField(blank=True, max_length=120, verbose_name='kargu')),
                ('habilitasaun_literaria', models.CharField(blank=True, max_length=120, verbose_name='habilitasaun literária')),
                ('disiplina_hanorin', models.CharField(blank=True, max_length=255, verbose_name='disiplina hanorin')),
                ('nu_kontaktu', models.CharField(blank=True, max_length=20, verbose_name='nu. kontaktu')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='foto')),
                ('nivel_edukasaun', models.CharField(blank=True, choices=[('ENSINU_SEKUNDARIU', 'Ensinu Sekundáriu'), ('DIPLOMA', 'Diploma'), ('BACHARELATU', 'Bacharelatu'), ('LICENCIADO', 'Licenciado'), ('POST_GRADUACAO', 'Post Graduação'), ('MESTRADO', 'Mestradu'), ('DOUTORAMENTU', 'Doutoramentu')], max_length=20, verbose_name='nivel edukasaun')),
                ('area_estudu', models.CharField(blank=True, max_length=120, verbose_name='aréa estudu')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['naran_kompletu'],
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
