# Generated by Django 6.0.7 on 2026-08-03 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numeru_id',
            field=models.PositiveIntegerField(default=1, help_text="Numeru ne'ebé identifika profesór/a iha lista eskola nian.", unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='numeru ID'),
            preserve_default=False,
        ),
    ]
