# Generated by Django 6.0.7 on 2026-08-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_numeru_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administradór'), ('PROFESSOR', 'Professór')], default='PROFESSOR', max_length=20, verbose_name='role'),
        ),
    ]
