# Generated by Django 6.0.3 on 2026-08-10 00:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.foto_perfil, verbose_name='foto'),
        ),
    ]
