# Generated by Django 6.0.3 on 2026-08-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nivel_edukasaun',
            field=models.CharField(blank=True, choices=[('ENSINU_SEKUNDARIU', 'Ensinu Sekundáriu'), ('DIPLOMA', 'Diploma'), ('FINALISTA', 'Finalista'), ('UNIVERSITARIA', 'Universitária'), ('BACHARELATU', 'Bacharelato'), ('LICENCIADO', 'Licenciado'), ('POST_GRADUACAO', 'Post Graduacao'), ('MESTRADO', 'Mestradu'), ('DOUTORAMENTU', 'Doutoramentu')], max_length=20, verbose_name='nivel edukasaun'),
        ),
    ]
