# Generated by Django 6.0.7 on 2026-08-12 13:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_nivel_edukasaun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.ImageField(blank=True, default='fotos/default.jpg', null=True, upload_to=accounts.models.foto_perfil, verbose_name='foto'),
        ),
    ]
