# Generated by Django 6.0.7 on 2026-08-03 01:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrezensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kargu', models.CharField(blank=True, max_length=120, verbose_name='kargu')),
                ('fulan', models.PositiveSmallIntegerField(choices=[(1, 'Janeiru'), (2, 'Fevereiru'), (3, 'Marsu'), (4, 'Abril'), (5, 'Maiu'), (6, 'Juñu'), (7, 'Jullu'), (8, 'Agostu'), (9, 'Setembru'), (10, 'Outubru'), (11, 'Novembru'), (12, 'Dezembru')], verbose_name='fulan')),
                ('tinan', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='tinan')),
                ('kriadu_iha', models.DateTimeField(auto_now_add=True, verbose_name='kriadu iha')),
                ('atualiza_iha', models.DateTimeField(auto_now=True, verbose_name='atualiza iha')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lista_prezensa', to=settings.AUTH_USER_MODEL, verbose_name='profesór/a')),
            ],
            options={
                'verbose_name': 'lista prezensa',
                'verbose_name_plural': 'lista prezensa',
                'ordering': ['-tinan', '-fulan', 'profesor__naran_kompletu'],
            },
        ),
        migrations.CreateModel(
            name='Prezensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='data')),
                ('oras_dader_tama', models.TimeField(blank=True, null=True, verbose_name='oras dader tama')),
                ('foto_dader_tama', models.ImageField(blank=True, null=True, upload_to='prezensa/%Y/%m/', verbose_name='foto dader tama')),
                ('oras_dader_fila', models.TimeField(blank=True, null=True, verbose_name='fila dader')),
                ('foto_dader_fila', models.ImageField(blank=True, null=True, upload_to='prezensa/%Y/%m/', verbose_name='foto fila dader')),
                ('oras_lorokraik_tama', models.TimeField(blank=True, null=True, verbose_name='oras lorokraik tama')),
                ('foto_lorokraik_tama', models.ImageField(blank=True, null=True, upload_to='prezensa/%Y/%m/', verbose_name='foto lorokraik tama')),
                ('oras_lorokraik_fila', models.TimeField(blank=True, null=True, verbose_name='fila lorokraik')),
                ('foto_lorokraik_fila', models.ImageField(blank=True, null=True, upload_to='prezensa/%Y/%m/', verbose_name='foto fila lorokraik')),
                ('estadu', models.CharField(choices=[('PREZENTE', 'Prezente'), ('FALTA', 'Falta'), ('LISENSA', 'Lisensa'), ('MISAUN', 'Misaun'), ('FERIADU', 'Feriadu')], default='PREZENTE', max_length=10, verbose_name='estadu')),
                ('obs', models.TextField(blank=True, verbose_name='obs')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prezensa', to='attendance.listaprezensa', verbose_name='lista prezensa')),
            ],
            options={
                'verbose_name': 'prezensa',
                'verbose_name_plural': 'prezensa',
                'ordering': ['data'],
            },
        ),
        migrations.AddConstraint(
            model_name='listaprezensa',
            constraint=models.UniqueConstraint(fields=('profesor', 'fulan', 'tinan'), name='unique_lista_prezensa_profesor_fulan_tinan'),
        ),
        migrations.AddConstraint(
            model_name='prezensa',
            constraint=models.UniqueConstraint(fields=('lista', 'data'), name='unique_prezensa_lista_data'),
        ),
    ]
