# Generated by Django 6.0.3 on 2026-08-03 02:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prezensa',
            name='foto_dader_fila',
        ),
        migrations.RemoveField(
            model_name='prezensa',
            name='foto_dader_tama',
        ),
        migrations.RemoveField(
            model_name='prezensa',
            name='foto_lorokraik_fila',
        ),
        migrations.RemoveField(
            model_name='prezensa',
            name='foto_lorokraik_tama',
        ),
        migrations.RemoveField(
            model_name='prezensa',
            name='oras_dader_fila',
        ),
        migrations.RemoveField(
            model_name='prezensa',
            name='oras_dader_tama',
        ),
        migrations.RemoveField(
            model_name='prezensa',
            name='oras_lorokraik_fila',
        ),
        migrations.RemoveField(
            model_name='prezensa',
            name='oras_lorokraik_tama',
        ),
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesaun', models.CharField(choices=[('DADER', 'Dader'), ('LOROKRAIK', 'Lorokraik')], max_length=10, verbose_name='sesaun')),
                ('tipu', models.CharField(choices=[('TAMA', 'Tama'), ('FILA', 'Fila')], max_length=4, verbose_name='tipu')),
                ('oras', models.TimeField(verbose_name='oras')),
                ('rejistu_iha', models.DateTimeField(auto_now_add=True, verbose_name='rejistu iha')),
                ('foto', models.ImageField(upload_to='prezensa/%Y/%m/', verbose_name='foto')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude')),
                ('presizaun', models.FloatField(blank=True, null=True, verbose_name='presizaun')),
                ('distansia_metru', models.FloatField(blank=True, null=True, verbose_name='distánsia (m)')),
                ('iha_eskola', models.BooleanField(blank=True, null=True, verbose_name='iha eskola')),
                ('prezensa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marka', to='attendance.prezensa', verbose_name='prezensa')),
            ],
            options={
                'verbose_name': 'marka',
                'verbose_name_plural': 'marka',
                'ordering': ['prezensa__data', 'oras'],
                'constraints': [models.UniqueConstraint(fields=('prezensa', 'sesaun', 'tipu'), name='unique_marka_prezensa_sesaun_tipu')],
            },
        ),
    ]
