# Generated by Django 6.0.3 on 2026-08-10 00:23

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rename_estadu_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marka',
            name='foto',
            field=models.ImageField(upload_to=attendance.models.foto_marka, verbose_name='foto'),
        ),
    ]
